version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306"
    networks:
      - red-backend
  cliente:
    build:
      context: .
      dockerfile: Dockerfile.cliente
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - red-backend
  administracion:
    build:
      context: .
      dockerfile: Dockerfile.administracion
    ports:
      - "5010:5000"
    depends_on:
      - db
    networks:
      - red-backend
  nginx:
    image: nginx:latest
    volumes:
      - ./Backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cliente
      - administracion
      #- server2
    ports:
      - "5020:5000"
    networks:
      - red-backend
networks:
  #se crea la red "red-servidores" usando el driver de tipo "bridge"
  red-backend:
    driver: bridge