version: "3.9"
services:
  cliente:
    image: wygd/ms-cliente:test
    ports:
      - "5010:5000"
    networks:
      - red-backend
  administracion:
    image: wygd/ms-administracion:test
    ports:
      - "5020:5000"
    networks:
      - red-backend
  servicio_administrativo:
    image: wygd/ms-serv-admin:test
    ports:
      - "5030:5000"
    networks:
      - red-backend
  usuario:
    image: wygd/ms-usuario:test
    ports:
      - "5040:5000"
    networks:
      - red-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.usuario
  #   ports:
  #     - "5040:5000"
  #   networks:
  #     - red-backend
  # reporte:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.reporte
  #   ports:
  #     - "5050:5000"
  #   networks:
  #     - red-backend
  # prediccion:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prediccion
  #   ports:
  #     - "5060:5000"
  #   networks:
  #     - red-backend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cliente
      - administracion
      - servicio_administrativo
      - usuario
    ports:
      - "5000:5000"
    networks:
      - red-backend
networks:
  #se crea la red "red-servidores" usando el driver de tipo "bridge"
  red-backend:
    driver: bridge