---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        remote_src: no
        src: nginx.conf
        dest: /etc/nginx/sites-available/nginx.conf
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: Creates directory
      file:
        path: /frontend
        state: directory
    - name: copy the content of the web site
      copy:
        src: ../Frontend/dist
        dest: /Frontend/
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes