---
- hosts: production
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        remote_src: no
        src: nginx-production.conf
        dest: /etc/nginx/sites-available/nginx.conf
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/nginx.conf
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: Creates directory
      file:
        path: Frontend_production
        state: directory
        owner: app-admin
        group: app-admin
        mode: 0755
      become: yes
    - name: copy the content of the web site
      copy:
        remote_src: no
        src: ../FrontendUI/dist/
        dest: Frontend_production
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes